CREATE TABLE IF NOT EXISTS project_details (
    project_id INT AUTO_INCREMENT PRIMARY KEY,
    client_id INT NOT NULL,
    application_name VARCHAR(100) NOT NULL,
    production_url VARCHAR(255),
    testing_environment VARCHAR(255),
    application_type VARCHAR(50),
    authentication_method VARCHAR(100),
    user_roles VARCHAR(100),
    session_management VARCHAR(100),
    session_timeout_period INT,
    total_num_input_fields INT,
    input_types_present VARCHAR(100),
    sensitive_data_handled VARCHAR(100),
    data_storage VARCHAR(100),
    number_of_endpoints INT,
    authentication_required BOOLEAN,
    rate_limiting BOOLEAN,
    documentation_available BOOLEAN,
    security_controls_present VARCHAR(100),
    hosting VARCHAR(255),
    critical_functions VARCHAR(100),
    compliance_requirements VARCHAR(50),
    previous_testing DATE,
    time_restrictions VARCHAR(100),
    testing_limitations VARCHAR(100),
    required_reports VARCHAR(100),
    project_start_date DATE,
    draft_report_due_date DATE,
    final_report_due_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(client_id) ON DELETE CASCADE
);