CREATE TABLE IF NOT EXISTS project_details (
    project_id INT AUTO_INCREMENT PRIMARY KEY,
    client_id INT NOT NULL,
    application_name VARCHAR(100) NOT NULL,
    production_url VARCHAR(255),
    testing_environment JSON,
    application_type JSON,
    authentication_method JSON,
    user_roles JSON,
    session_management JSON,
    session_timeout_period INT,
    total_num_input_fields INT,
    input_types_present JSON,
    sensitive_data_handled JSON,
    data_storage JSON,
    number_of_endpoints INT,
    authentication_required varchar(10),
    rate_limiting varchar(10),
    documentation_available varchar(10),
    security_controls_present JSON,
    hosting JSON,
    critical_functions JSON,
    compliance_requirements JSON,
    previous_testing DATE,
    time_restrictions JSON,
    testing_limitations JSON,
    required_reports JSON,
    project_start_date DATE,
    draft_report_due_date DATE,
    final_report_due_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(client_id) ON DELETE CASCADE
);